### ISSUE TITLE
Vaccination vs case rates graph

### ISSUE THREAD

**Issue by sharpie7** [russss/covidtracker#16]
Thanks again for a great visualization tool. After the last update I am missing the nice graph of case rates Vs vaccination rates that used to be on the vaccination tab. I always liked this because the “tails” showing the history were great for visualizing the trends. It was also rather curious because generally the trend sloped the “wrong” way (higher vaccination trends to higher reported rates) so I wanted to keep an eye on how that evolved. Any chance it could be restored?

Will you be adding a “booster” graph to the vaccination page?

**Comment by russss** [comment]
I've removed it because the vaccination percentage was unlikely to be informative any more - I do agree it was (unintentionally) quite interesting for other reasons, but I think the vaccination rate axis was misleading.

I'm currently pondering whether it's worth trying to do something more fancy for estimating effective vaccine coverage.

I've added third doses to the rest of the vaccine graphs, and that will appear once COG-UK has fixed their TLS certificate which is causing my build to fail.
