### ISSUE TITLE
Enhancement: Include age data in analysis

### ISSUE THREAD

**Issue by sharpie7** [russss/covidtracker#3]
Thanks for the best tool that I know to visualize UK Covid data.

At the moment it is being widely asserted that the rising cases is associated more with the younger part of the population than the older. If possible, it would be useful if this tool can also show information related to the ages of people with covid infections so we could see how the spread is changing with respect to age as well as geography.

**Comment by russss** [comment]
Thanks!

I agree that it would be very nice to have this, unfortunately the coronavirus.data.gov.uk API does not provide a time series of infection rates by age at the moment (it does have some data by age, but it's only available as a total rather than as a time series, which makes it pretty useless).

Public Health England does publish this data in their weekly report, but only by week and the data tables are in an Excel spreadsheet.

It is certainly possible for me to scrape the appropriate Excel spreadsheet off gov.uk and parse it - I was doing this for some different data earlier in the pandemic - but I thought we were past this now, and I'm not sure how useful the weekly data will be. I may give it a try.

Until then, Colin on Twitter [has visualised exactly this data](https://twitter.com/VictimOfMaths/status/1305084477782319106) from last Friday's PHE report.

**Comment by sharpie7** [comment]
Thanks for the info and the link - much appreciated.

Shame the data isn't in the API.

**Comment by russss** [comment]
Oh, I added this a while back now.
