### ISSUE TITLE
Change shading could be based on % not absolute? 

### ISSUE THREAD

**Issue by dsyme** [russss/covidtracker#7]
The change shading is chosen by absolute number, so -52 is dark green for example, even when the change is 1100 to 1049.

It feels the shading should be chosen by % change instead to prevent a false picture

Or else % change and absolute change as separate selections.

Great tool, thanks

**Comment by russss** [comment]
There's not really a good solution here - the change numbers were actually originally percentages but I changed them to absolute numbers because percentages are misleadingly noisy when the total number of cases is low (which is, I admit, not really an issue at the moment).

I'm inclined to stick with the absolute numbers because they do still work when totals are high.

**Comment by dsyme** [comment]
OK, I see, thanks
